### ISSUE TITLE
Band buckets must be per-partner

### ISSUE THREAD

**Issue by tpolecat** [gemini-hlsw/itac-cli#9]
Right each band has a single bucket of time, based on the total number of available hours in the semester, and partners get slices of this time based on their partner share. There are several problems with this:

- We sometimes need to move time between bands and/or partners for various reasons, so the times are not actually computable from share percentages.
- We want to be able to construct the queue iteratively, as each batch of proposals arrive. however as it stands now the first partner's programs will all go into band 1 because there is nobody else competing for that time yet.

The proposed solution is to have explicit buckets in the configuration, like this:

```yaml
hours:
  US: 226.5 247.8 165.2
  CA:  60.5  66.2  44.2
  AR:  11.3  11.3   7.5
  BR:  23.8  23.8  15.9
  KR:  18.2  18.2  12.2
  CL:  43.2  43.2  28.8
  LP:  27.0   0.0   0.0
```

And then the queue engine deducts time from each bucket independently.
